apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      httpMethod: "POST"

  - name: Jenkins
    type: prometheus
    access: proxy
    url: http://jenkins:8080/prometheus
    editable: true
    jsonData:
      timeInterval: "30s"
