jenkins:
  systemMessage: "Jenkins configurado automáticamente para el proyecto Villa Alfredo"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 3
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin123"
          
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"

  remotingSecurity:
    enabled: true

  clouds:
    - docker:
        name: "docker-cloud"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "nodejs-agent"
            dockerTemplateBase:
              image: "ci-cd_nodejs-agent:latest"
              pullCredentialsId: ""
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "3"
            retentionStrategy:
              idleMinutes: 10
              
          - labelString: "terraform-agent"
            dockerTemplateBase:
              image: "ci-cd_terraform-agent:latest"
              pullCredentialsId: ""
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "2"
            retentionStrategy:
              idleMinutes: 10
              
          - labelString: "security-agent"
            dockerTemplateBase:
              image: "ci-cd_security-agent:latest"
              pullCredentialsId: ""
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "2"
            retentionStrategy:
              idleMinutes: 10
              
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "ci-cd_docker-agent:latest"
              pullCredentialsId: ""
              privileged: true
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "2"
            retentionStrategy:
              idleMinutes: 10

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

unclassified:
  location:
    url: "http://localhost:8080/"
    adminAddress: "admin@villalfredo.com"

  mailer:
    charset: "UTF-8"
    useSsl: false
    smtpHost: "localhost"
    defaultSuffix: "@villalfredo.com"

  sonarGlobalConfiguration:
    installations:
      - name: "SonarQube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonarqube-token"

  globalLibraries:
    libraries:
      - name: "shared-library"
        defaultVersion: "main"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/your-org/jenkins-shared-library.git"

jobs:
  - script: |
      pipelineJob('villa-alfredo-backend-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/your-org/villa-alfredo.git')
                  credentials('github-credentials')
                }
                branch('*/main')
              }
            }
            scriptPath('ci-cd/Jenkinsfile')
          }
        }
        triggers {
          scm('H/5 * * * *')
          githubPush()
        }
      }

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-credentials"
              username: "${GITHUB_USERNAME}"
              password: "${GITHUB_TOKEN}"
              description: "GitHub Access Token"
          - string:
              scope: GLOBAL
              id: "sonarqube-token"
              secret: "${SONARQUBE_TOKEN}"
              description: "SonarQube Token"
          - aws:
              scope: GLOBAL
              id: "aws-credentials"
              accessKey: "${AWS_ACCESS_KEY_ID}"
              secretKey: "${AWS_SECRET_ACCESS_KEY}"
              description: "AWS Credentials"
