version: '3.8'
services:
  grafana:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  grafana-init:
    image: alpine:latest
    depends_on:
      - grafana
    volumes:
      - ./configure_grafana.sh:/configure_grafana.sh:ro
      - ./dashboards:/dashboards:ro
    entrypoint: ["sh", "-c", "apk add --no-cache curl jq >/dev/null && sleep 20 && sh /configure_grafana.sh"]

volumes:
  grafana_data: