services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-terraform
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Persistir datos de Jenkins
      - jenkins_home:/var/jenkins_home
      
      # Acceso al socket de Docker (para Docker-in-Docker)
      - /var/run/docker.sock:/var/run/docker.sock
      
      # Montar el directorio del proyecto
      - ../:/workspace
      
      # Credenciales de AWS (opcional, si tienes configuradas localmente)
      - ~/.aws:/var/jenkins_home/.aws:ro
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-network

  # Opcional: Contenedor de PostgreSQL para almacenar datos de Jenkins
  jenkins-db:
    image: postgres:13
    container_name: jenkins-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jenkins
      POSTGRES_USER: jenkins
      POSTGRES_PASSWORD: jenkins123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jenkins-network

volumes:
  jenkins_home:
    driver: local
  postgres_data:
    driver: local

networks:
  jenkins-network:
    driver: bridge
